kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocal: TCP
    port: 8020
    nodePort: 8020
    
    
 ---
 
 apVersion: extensions/vibetal
 kind: Deployment
 metadata:
   name: train-schedule-deployment
   labels:
     app: train-schedule
 spec:
   replicas: 2
   selector:
     matchLables:
       app: train-schedule
   template:
     metadata:
       lables:
         app: train-schedule
  spec:
    containers:
    - name: train-schedule
      image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
      ports:
      - containerPort:8020
  
